#!/usr/bin/env bash
# process with PID file and signal handling
echo $$ > /tmp/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /tmp/myscript.pid; exit' SIGQUIT SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
done
